### ISSUE TITLE
建议增加删除按钮

### ISSUE THREAD

**Issue by wnma3mz** [zhzy0077/pipehub#11]
已在GitHub中Setting部分删除了授权，但依旧可以使用PipeHub的推送。。。能否增加一个删除功能？

**Comment by zhzy0077** [comment]
感谢反馈。
- 目前这个 Issue 的原因: GitHub 的 OAuth 登录在被 Revoke 的时候没有回调 , PipeHub这边收不到您删除的通知。
- 我们提供的缓解方案: 您可以在删除 OAuth 授权前删除您填写的微信企业ID等信息，保存后就无法向您发送消息了。
- 后续改进: 因为没有回调的原因，很难做一个体验完全比删除企业ID更好的删除功能，会先在文档中添加有关删除的内容。

PS：方便了解下您是因为什么想要删除吗？

**Comment by wnma3mz** [comment]
感谢您的回复。删除功能只是我的一项建议，实际并不影响任何使用体验~

根据您提供的企业微信方式，我自己查阅了一下企业微信的开发文档。发现如果是自用的话，自己去拿access_token请求也很方便。并且实际测试下来，由于不需要请求您的域名，所以速度也上会更快。

您的项目会比独立开发更加方便。但由于目前我只是个人使用，所以暂时不需要您开发的服务也能满足需求。再次感谢您的项目，给予了我很大帮助。：)

**Comment by zhzy0077** [comment]
感谢您的使用哈，因为服务器在国外的缘故，速度上肯定也是直接请求企业微信API更快。对于可以自己编程的场景我也推荐是自己请求即可。
那我 Close 这个 Issue 啦。
