### ISSUE TITLE
Dependency("invalid uri character")

### ISSUE THREAD

**Issue by wnma3mz** [zhzy0077/pipehub#2]
按照https://www.pipehub.net/#/网页上的配置完成后，得到了Callback URL。

`https://www.pipehub.net/send/code?txt=helloword`

code为获取到的App Key，我理解GET请求可以通过浏览器打开这个链接发送通知，但我打开后得到了

`Dependency("invalid uri character")`

希望能得到回复，感谢大佬开发的这个项目！

**Comment by zhzy0077** [comment]
Thanks for your testing and feedback. I'm actively investigating this issue. Thanks for the patience.

**Comment by zhzy0077** [comment]
@wnma3mz Hi, I just checked our service. It seems the secret you pasted in has a leading space. Could you have a try to remove the extra space? 
========
你好，我刚刚查询了下，您的微信Secret开头似乎有个空格，能否去掉再尝试下呢？

**Comment by wnma3mz** [comment]
感谢您这么迅速的回复，已删除空格，验证有效！谢谢！

**Comment by zhzy0077** [comment]
感谢使用，会在下个release的时候加上空格的过滤的。😊
