### ISSUE TITLE
Enhancement: Allow user to choose a department when sending the message. 

### ISSUE THREAD

**Issue by wnma3mz** [zhzy0077/pipehub#5]
目前似乎是根据一个GitHub账号绑定一个App Key，对应一个企业微信。

但一个企业微信是可以开多个应用，App Key能否根据GitHub账号+Agent ID来生成。

这样一个企业微信就可以根据不同的联系人，推送不同的消息

**Comment by zhzy0077** [comment]
感谢反馈。如果需求是给不同的联系人发送消息的话，支持在发送的时候指定接受人是不是会更方便解决这个问题？

**Comment by wnma3mz** [comment]
> 感谢反馈。如果需求是给不同的联系人发送消息的话，支持在发送的时候指定接受人是不是会更方便解决这个问题？

感谢您的迅速回复，但一个应用不是指定了某个标签的群体吗？这样的话就只能一直固定给这个群体发消息，或者需要每次手动更改接受人。我想对于其他群体发送不同的消息通知就不是很好处理了

**Comment by zhzy0077** [comment]
现在的实现里是固定的的 `to_user: "@all"` 也就是给这个应用覆盖的所有用户发送。我现在有两个思路：
- 一个是通过在每次发送的时候指定要发送的人（就是这个账号ID）通过 | 或者啥符号分割：
![image](https://user-images.githubusercontent.com/8717471/83590799-23ec1b00-a589-11ea-9fce-6814ae62f3cc.png)
- 第二个是通过部门来分群体，一个人可以在多个部门里，在发送时指定一个部门ID：
![image](https://user-images.githubusercontent.com/8717471/83591140-d1f7c500-a589-11ea-98d5-fe7064156c2a.png)

我直觉上看是人少的时候第一种方便，人多的话第二种容易管理，能详细描述下你的场景吗？

**Comment by wnma3mz** [comment]
> 现在的实现里是固定的的 `to_user: "@all"` 也就是给这个应用覆盖的所有用户发送。我现在有两个思路：
> 
> * 一个是通过在每次发送的时候指定要发送的人（就是这个账号ID）通过 | 或者啥符号分割：
>   ![image](https://user-images.githubusercontent.com/8717471/83590799-23ec1b00-a589-11ea-9fce-6814ae62f3cc.png)
> * 第二个是通过部门来分群体，一个人可以在多个部门里，在发送时指定一个部门ID，也可以是名字之类的：
>   ![image](https://user-images.githubusercontent.com/8717471/83591140-d1f7c500-a589-11ea-98d5-fe7064156c2a.png)
> 
> 我直觉上看是人少的时候第一种方便，人多的话第二种容易管理，能详细描述下你的场景吗？

我个人更倾向于第二种。我自己是想做类似订阅通知服务这种，定时爬取并推送感兴趣的新闻标题和摘要。您这种服务，对于个人来使用自然没有问题，但我后续想同样给我的朋友使用。

比如有A、B、C三种资讯，有三种类型的好友甲乙丙。甲标签用户想同时订阅A、B、C，乙只想订阅A，乙想订阅B、C。

因此更倾向于第二种。目前只是一个设想，实际用户规模也不会很庞大，所以两种实际差不多。

**Comment by zhzy0077** [comment]
有道理，我其实也更倾向通过部门/组织去管理这个，加到 TODO 里了哈
